## OpenCV
OpenCV is a library of programming functions mainly aimed at real-time computer vision. Originally developed by Intel, it was later supported by Willow Garage then Itseez.

OpenCV is available in C++,Java and Python

### Installation

pip install opencv-python <br>
pip install opencv-contrib-python

In [1]:
#import package
import cv2 as cv
import numpy as np

In [2]:
#Load Image
img = cv.imread("data/lena.jpg")

In [3]:
#type of img - every image is a numerical array.
type(img)

numpy.ndarray

In [4]:
#Image Shape
img.shape  #Height,Width,Layers(Blue,Green,Red) 

(512, 512, 3)

In [51]:
print(img[0])

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]
  ...
  [ 5  5  5]
  [ 5  5  5]
  [ 5  5  5]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[31 31 31]
  [31 31 31]
  [30 30 30]
  ...
  [71 71 71]
  [67 67 67]
  [63 63 63]]]


In [5]:
#Show Lena Image
cv.namedWindow('Lena', cv.WINDOW_AUTOSIZE)
cv.imshow('Lena', img)
cv.waitKey(10000) #wait 10 seconds
cv.destroyAllWindows()

In [6]:
img.min()   #0 meaning zero light and 255 meaning maximum light

0

In [7]:
img.max()

255

In [9]:
#Load image as greyscale
img_grey = cv.imread("data/messi.jpg", cv.IMREAD_GRAYSCALE)
cv.imshow('Messi BW', img_grey)
cv.waitKey(10000)
cv.destroyAllWindows()

In [10]:
img_grey.shape #Height, Width

(750, 1200)

In [14]:
750*1200

900000

In [15]:
img_grey.size

900000

In [11]:
img = cv.imread("data/messi.jpg")

In [12]:
#Show Image
cv.namedWindow('Messi Normal Image', cv.WINDOW_AUTOSIZE)
cv.imshow('Messi photo', img)
cv.waitKey(10000)
cv.destroyAllWindows()

In [10]:
#Show GreyScale Image
cv.namedWindow('Messi_Grey', cv.WINDOW_AUTOSIZE)
cv.imshow('Messi_Grey', img_grey)
cv.waitKey(10000)
cv.destroyAllWindows()

In [17]:
##Binary Image(#points upto 127 will 0 and greater will be 1)
thresh, im_bw = cv.threshold(img_grey, 127, 255,  
                               cv.THRESH_BINARY)

In [28]:
##Binary Image
im_bw = cv.threshold(img_grey, 127, 255, cv.THRESH_BINARY)[1]

In [29]:
#Show Binary Image
cv.namedWindow('MessiBinary', cv.WINDOW_AUTOSIZE)
cv.imshow('Messi_Binary', im_bw)
cv.waitKey(10000)
cv.destroyAllWindows()

In [47]:
a= np.array([[1,2,5],[1,25,14]])

In [48]:
a

array([[ 1,  2,  5],
       [ 1, 25, 14]])

In [49]:
a.shape

(2, 3)

In [50]:
img.shape

(750, 1200, 3)

In [30]:
#Accessing pixel intensity values

blue = img[:,:,0]
green = img[:,:,1]
red = img[:,:,2]

In [31]:
#Show GreyScale Image
cv.namedWindow('Blue Image', cv.WINDOW_AUTOSIZE)
cv.imshow('Blue Image', blue)
cv.waitKey(5000)
cv.destroyAllWindows()

In [32]:
#Show GreyScale Image
cv.namedWindow('Green Image', cv.WINDOW_AUTOSIZE)
cv.imshow('Green Image', green)
cv.waitKey(5000)
cv.destroyAllWindows()

In [33]:
#Show GreyScale Image
cv.namedWindow('Red Image', cv.WINDOW_AUTOSIZE)
cv.imshow('Red Image', red)
cv.waitKey(5000)
cv.destroyAllWindows()

### Image Reconstruction

In [39]:
recons_image = np.dstack((red,green,blue))


In [40]:
recons_image.shape

(750, 1200, 3)

In [41]:
#Show GreyScale Image
cv.namedWindow('RE Image', cv.WINDOW_AUTOSIZE)
cv.imshow('RE Image', recons_image)
cv.waitKey(5000)
cv.destroyAllWindows()

In [20]:
recons_image.shape

(750, 1200, 3)

In [21]:
#Save Image
cv.imwrite("data/Messi_Grey.jpg",img_grey)

True

In [22]:
#Save Image
cv.imwrite("data/Messi_BW.jpg",im_bw)

True

In [23]:
#image datatype
type(img)

numpy.ndarray

### Creating A new Image

In [24]:
#new Image - Black Image
new_img = np.zeros((750,1200,3)) #with dim

In [25]:
new_img

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
#Show GreyScale Image
cv.namedWindow('New Image', cv.WINDOW_AUTOSIZE)
cv.imshow('New Image', new_img)
cv.waitKey(2000)
cv.destroyAllWindows()

In [27]:
#new Image - White Image
new_img[:] = 255

In [28]:
#Show GreyScale Image
cv.namedWindow('New Image', cv.WINDOW_AUTOSIZE)
cv.imshow('New Image', new_img)
cv.waitKey(5000)
cv.destroyAllWindows()

### Contrast & Brightness

#### Two commonly used point processes are multiplication and addition with a constant: g(x )= αf(x) + β

The parameters α>0 and β are often called the gain and bias parameters; sometimes these parameters are said to control contrast and brightness respectively.

In [13]:
new_image = np.zeros(img.shape, img.dtype)

In [14]:
alpha = .5    #Simple contrast control
beta = -20   #Simple brightness control

### alpha  = 2
### beta    = 20

#### Actual pixel value (100,100,100)
#### Processed value (220,220,220)

In [15]:
#for y in range(img.shape[0]):
#    for x in range(img.shape[1]):
#        for c in range(img.shape[2]):
#            new_image[y,x,c] = np.clip(alpha*img[y,x,c] + beta, 0, 255)

In [16]:
#Show GreyScale Image
cv.namedWindow('New Image', cv.WINDOW_AUTOSIZE)
cv.imshow('New Image', new_image)
cv.waitKey(5000)
cv.destroyAllWindows()

### Gamma correction

Gamma correction can be used to correct the brightness of an image by using a non linear transformation between the input values and the mapped output values:

O = (I/255)^γ * 255

When γ<1, the original dark regions will be brighter and the histogram will be shifted to the right whereas it will be the opposite with γ>1.

In [206]:
gamma = 4
lookUpTable = np.empty((1,256), np.uint8)
for i in range(256):
    lookUpTable[0,i] = np.clip(pow(i / 255.0, gamma) * 255.0, 0, 255)
res = cv.LUT(img, lookUpTable)

In [208]:
#Show gamma corrected Image
cv.namedWindow('gamma Image', cv.WINDOW_AUTOSIZE)
cv.imshow('gamma Image', res)
cv.waitKey(5000)
cv.destroyAllWindows()

### Adding (blending) two images using OpenCV

##### g(x) = (1−α) f0(x) + αf1(x)

In [35]:
img2 = cv.imread("data/ground.jpg")
img2 = cv.resize(img2,(img.shape[1],img.shape[0]))



In [36]:
#Show Blended Image
cv.namedWindow('ground Image', cv.WINDOW_AUTOSIZE)
cv.imshow('ground Image', img2)
cv.waitKey(5000)
cv.destroyAllWindows()

In [37]:
alpha = 0.9
beta = (1.0 - alpha)

res = cv.addWeighted(img, alpha, img2, beta, 0.0)

In [38]:
#Show Blended Image
cv.namedWindow('blended Image', cv.WINDOW_AUTOSIZE)
cv.imshow('blended Image', res)
cv.waitKey(5000)
cv.destroyAllWindows()

### Canny Edge

In [57]:
edges = cv.Canny(img_grey,150,150)

In [59]:
#Show Edges
cv.namedWindow('Edges', cv.WINDOW_AUTOSIZE)
cv.imshow('Edges', edges)
cv.waitKey(5000)
cv.destroyAllWindows()

### Add Text 

In [17]:
img_text = img.copy()

# font 
font = cv.FONT_HERSHEY_SIMPLEX 
  
# org 
org = (225, 225) 
  
# fontScale 
fontScale = 2
   
# Blue color in BGR 
color = (55, 75, 150) 
  
# Line thickness of 2 px 
thickness = 5
   
# Using cv2.putText() method 
img_text = cv.putText(img_text, 'The Goat!', org, font,  
                   fontScale, color, thickness, cv.LINE_AA) 

In [18]:
#Show Text on Image
cv.namedWindow('text Image', cv.WINDOW_AUTOSIZE)
cv.imshow('text Image', img_text)
cv.waitKey(5000)
cv.destroyAllWindows()

### Gaussian Blur

In [19]:
img_blur = cv.GaussianBlur(img,(9,9),0)

In [20]:
#Show Blur Image
cv.namedWindow('blur Image', cv.WINDOW_AUTOSIZE)
cv.imshow('blur Image', img_blur)
cv.waitKey(2000)
cv.destroyAllWindows()

### Dilation and erosion are two fundamental morphological operations. Dilation adds pixels to the boundaries of objects in an image, while erosion removes pixels on object boundaries. The number of pixels added or removed from the objects in an image depends on the size and shape of the structuring element used to process the image.

In [171]:
#Load Image
img = cv.imread("data/j2.png")

In [172]:
#Show actual Image
cv.namedWindow('actual Image', cv.WINDOW_AUTOSIZE)
cv.imshow('actual Image', img)
cv.waitKey(5000)
cv.destroyAllWindows()

### Image Dilation

In [173]:
# creating kernals
kernal = np.ones((5,5),np.uint8)
img_dilate = cv.dilate(img,kernal,iterations = 1)

In [174]:
#Show dilation Image
cv.namedWindow('dilate Image', cv.WINDOW_AUTOSIZE)
cv.imshow('dilate Image', img_dilate)
cv.waitKey(5000)
cv.destroyAllWindows()

### Image Erosion

In [175]:
# creating kernals
kernal = np.ones((5,5),np.uint8)
img_erode = cv.erode(img,kernal,iterations = 5)

In [176]:
#Show Erode Image
cv.namedWindow('erode Image', cv.WINDOW_AUTOSIZE)
cv.imshow('erode Image', img_erode)
cv.waitKey(2000)
cv.destroyAllWindows()

## opening - morphologyEx

Opening is just another name of erosion followed by dilation. It is useful in removing noise

In [177]:
opening = cv.morphologyEx(img, cv.MORPH_OPEN, kernal)

In [178]:
#Show opening Image
cv.namedWindow('opening Image', cv.WINDOW_AUTOSIZE)
cv.imshow('opening Image', opening)
cv.waitKey(5000)
cv.destroyAllWindows()

### Closing  - morphologyEx

Closing is reverse of Opening, Dilation followed by Erosion. It is useful in closing small holes inside the foreground objects, or small black points on the object.

In [179]:
closing = cv.morphologyEx(img, cv.MORPH_CLOSE, kernal)

In [180]:
#Show closing Image
cv.namedWindow('closing Image', cv.WINDOW_AUTOSIZE)
cv.imshow('closing Image', closing)
cv.waitKey(5000)
cv.destroyAllWindows()

In [49]:
#END