In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### 0D

In [13]:
a0 = np.array(42)
print(a0)

42


In [21]:
a0.shape

()

### 1D - Series

In [18]:
a1 = np.array([10,11,12])  
print(a1)

[10 11 12]


In [26]:
a1.shape     #(Columns, Rows)

(3,)

### 2D

In [24]:
a2 = np.array([[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18],
               [19, 20, 21]])
print(a2)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [25]:
a2.shape     #(Columns, Rows)

(4, 3)

### 3D

In [2]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

In [3]:
a3.shape

(3, 3, 3)

In [7]:
print(a3[0])

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [9]:
print(a3[0,0,0])

10
